### ISSUE TITLE
Allow localhost without https

### ISSUE THREAD

**Issue by OR13** [digitalbazaar/credential-handler-polyfill#26] opened 2022-07-12 16:32 UTC
<img width="523" alt="Screen Shot 2022-07-12 at 11 32 07 AM" src="https://user-images.githubusercontent.com/8295856/178545546-0ebd6d0b-ee94-43d7-8462-6ea7e13938f0.png">

**Comment by OR13** [comment] 2022-07-12 16:33
I suggest using `ngrok` as a work around until this is resolved.

**Comment by dlongley** [comment] 2022-07-12 16:46
The error has `https` in the URL. I'm not sure what is being requested here -- and if it's something browsers allow generally or not. If you need to do local development with a localhost server with a self-signed HTTPS cert (for example), just visit that site in the browser you're doing development in and accept a temporary exception. Then reload everything.

**Comment by OR13** [comment] 2022-07-13 14:01
I just ran the whole thing locally, and it does not work unless you access through an http tunnel, like ngrok.

Its possible localhost http support is no longer a thing, in which case, you should mention that you must access the wallet over https and offer easy tunnels, like ngrok for testing.

**Comment by dlongley** [comment] 2023-03-03 17:42
Closing as a duplicate of #28.

**Closed as completed by dlongley** 2023-03-03 17:42 UTC
